version: '3.7'
services:
  salt-master:
    build: .
    image: salt-base:latest
    entrypoint: [ "./master.sh" ]
  salt-minion:
    image: salt-base:latest
    entrypoint: [ "./minion.sh" ]
    depends_on:
      - salt-master
